set(_AMENT_PACKAGE_NAME "mini_project_hp")
set(mini_project_hp_VERSION "0.0.0")
set(mini_project_hp_MAINTAINER "user <user@todo.todo>")
set(mini_project_hp_BUILD_DEPENDS "rclcpp" "std_msgs" "geometry_msgs" "sensor_msgs" "qt_gui")
set(mini_project_hp_BUILDTOOL_DEPENDS "ament_cmake")
set(mini_project_hp_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "geometry_msgs" "sensor_msgs" "qt_gui")
set(mini_project_hp_BUILDTOOL_EXPORT_DEPENDS )
set(mini_project_hp_EXEC_DEPENDS "rclcpp" "std_msgs" "geometry_msgs" "sensor_msgs" "qt_gui")
set(mini_project_hp_TEST_DEPENDS )
set(mini_project_hp_GROUP_DEPENDS )
set(mini_project_hp_MEMBER_OF_GROUPS )
set(mini_project_hp_DEPRECATED "")
set(mini_project_hp_EXPORT_TAGS)
list(APPEND mini_project_hp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
